### ISSUE TITLE
Substraction of block bit position from 64

### ISSUE THREAD

**Issue by Michael2280309** [dhuertas/DES#2]
The text block is a 64-bit integer. According to the initial permutation table we should have this algorithm:
- Get 58-th **highest** bit from text block. Thus we right shift block by (58-1) = 57 then bitwise AND-ing it with 1.
- But the code you wrote does right shifting by (64 - 58) = 6 positions. So we get the 7-th lower bit of the block instead of 58-th one.

Question: Are you considering the block to start from the **lowest** bit?

**Comment by dhuertas42** [comment]
You may have missed this when reading the DES FIPS document 😉

![image](https://github.com/dhuertas/DES/assets/144000595/00d3d3eb-e88e-4d1e-a5fb-28708811ff31)

**Comment by dhuertas** [comment]
Hi @Michael2280309,

You may have missed the footnote when reading the DES FIPS document 😉

![image](https://github.com/dhuertas/DES/assets/1814281/f95f96ec-930f-4bf3-bd9c-d1c9fd091fbe)
